spring:


  datasource:
    url: jdbc:mysql://your-rds-url:3306/aim?characterEncoding=UTF-8&serverTimezone=UTC
    username: your-username
    password: your-password
    driver-class-name:

    # jpa설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type: off # 실제 들어가는 파라미터값 찍어주는 설정

jwt:
  secret: ${JWT_SECRET_KEY} # base64 encoded & len > 32 여야함
  access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:30}
  refresh-token-expiration-weeks: ${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS:2}

cache:
  specs:
    refresh-token-uuid:
      expiration-week: ${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS:2}
      maximum-size: 10000
