spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # jpa설정
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 100

  # 로그 레벨 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [profile, email]

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: [profile_nickname]

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: off  # 실제 들어가는 파라미터값 찍어주는 설정
    org.hibernate.type: off

jwt:
  secret: ${JWT_SECRET_KEY} # base64 encoded & len > 32 여야함
  access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:30}
  refresh-token-expiration-weeks: ${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS:2}

cache:
  specs:
    refresh-token-uuid:
      expiration-week: ${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS:2}
      maximum-size: 10000

gemini:
  api-key: ${GEMINI_API_KEY}

app:
  cors:
    allowed-origins: ${APP_CORS_ORIGINS:}